### 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code that provides functionality to perform certain tasks or solve specific problems. These libraries contain modules, functions, and classes that can be imported and used in your Python programs to save time and effort. 

Python libraries enhance the efficiency and productivity of developers by offering pre-built solutions to common problems, promoting code reuse, and fostering a collaborative and extensible programming environment.

### 2. What is the difference between Numpy array and List?

•	Arrays in python can only contain elements of same data types i.e., data type of array should be homogeneous. consumes far less memory than lists. 

•	Lists in python can contain elements of different data types i.e., data type of lists can be heterogeneous. It has the disadvantage of consuming large memory.


In [3]:
import numpy as np

### 3. Find the shape, size and dimension of the following array?

In [5]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)

Shape: (3, 4)
Size: 12
Dimension: 2


### 4. Write python code to access the first row of the following array?

In [6]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("First row of the array:",arr[0])

First row of the array: [1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?

In [7]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("The element at the third row and forth column of the given array:",arr[2][3])

The element at the third row and forth column of the given array: 12


### 6. Write code to extract all odd-indexed elements from the given numpy array?

In [9]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("All odd-indexed elements from the given array", arr[:, 1::2])

All odd-indexed elements from the given array [[ 2  4]
 [ 6  8]
 [10 12]]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [12]:
import random
np.random.rand(3,3)

array([[0.41889802, 0.41234356, 0.51364169],
       [0.28038166, 0.49201037, 0.43984622],
       [0.62243995, 0.27942829, 0.69932741]])

### 8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand generates random values from a uniform distribution between 0 and 1.
np.random.randn generates random values from a standard normal distribution (mean=0, standard deviation=1).

### 9. Write code to increase the dimension of the following array?

In [20]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr1 = np.expand_dims(arr, axis = 1)
print("Dimension of original array:",arr.ndim)
print("After expanding the dimension of the original array:",arr1.ndim)
print(arr1)

Dimension of original array: 2
After expanding the dimension of the original array: 3
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


### 10. How to transpose the following array in NumPy?

In [22]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Original array:\n",arr)
print("Transpose of the given array:\n",arr.T)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose of the given array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Perform the following operation using Python:
1) Index wise multiplication
2) Matrix multiplication
3) Add both the matrices
4) Subtract matrix B from A
5) Divide matrix B by A

In [26]:
matrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matrixB = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("\nMatrix A\n",matrixA)
print("\nMatrix B\n",matrixB)
print("\nIndex-wise matrix multiplication\n",matrixA*matrixB)
print("\nAddition of both matrices\n",matrixA+matrixB)
print("\nSubtract matrix B from A\n",matrixA-matrixB)
print("\nDivide matrix B by A\n",matrixB/matrixA)


Matrix A
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Index-wise matrix multiplication
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Addition of both matrices
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtract matrix B from A
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Divide matrix B by A
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
matrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matrixB = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print("\nMatrix A\n",matrixA)
print("\nMatrix B\n",matrixB)
print("\nMatrix multiplication\n",matrixA@matrixB)


Matrix A
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Matrix multiplication
 [[ 70  80  90]
 [158 184 210]
 [246 288 330]]


### 12.  Which function in Numpy can be used to swap the byte order of an array?

In NumPy, you can use the byteswap function to swap the byte order of an array. The byteswap function creates a new array with the byte order swapped.

In [30]:
original_array = np.array([1, 256], dtype=np.int16)

print("Original Array:")
print(original_array)

# Swap the byte order
swapped_array = original_array.byteswap()

print("\nSwapped Array:")
print(swapped_array)

Original Array:
[  1 256]

Swapped Array:
[256   1]


### 13.  What is the significance of the np.linalg.inv function?
The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. In other words, it calculates the inverse of a square matrix, if it exists.

In [31]:
matrix = np.array([[4, 7],
                   [2, 6]])

inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)

Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


### 14. What does the np.reshape function do, and how is it used?
The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the same data but a different shape.

In [35]:
original_array = np.array([1, 2, 3, 4, 5, 6])
print("Original array:",original_array)
print("Dimension of original array:",original_array.ndim)
reshapped_array = original_array.reshape(1, 1, 2, 3)
print("Reshapped array:\n",reshapped_array)
print("Dimension of reshapped array:",reshapped_array.ndim)

Original array: [1 2 3 4 5 6]
Dimension of original array: 1
Reshapped array:
 [[[[1 2 3]
   [4 5 6]]]]
Dimension of reshapped array: 4


### 15. What is broadcasting in Numpy?

Broadcasting is a powerful feature in NumPy that allows arrays of different shapes to be combined or operated upon without the need for explicit conversion or duplication of data. Broadcasting automatically adjusts the shape of smaller arrays to match the shape of larger arrays, enabling element-wise operations.

In order for two arrays to be broadcast-compatible, the size of their dimensions must either be the same or one of them must be 1. NumPy performs the broadcasting according to the following rules:

1) If the arrays have a different number of dimensions:

Pad the smaller-dimensional array's shape with ones on its left side until the dimensions match.

2) If the sizes along a particular dimension are different:

If one of them is 1, then it is stretched to match the size of the other.
If neither is 1 and the sizes are different, broadcasting is not possible, and NumPy will raise a ValueError.

In [38]:
# Array A with shape (3, 1)
A = np.array([[1], [2], [3]])

# Array B with shape (1, 4)
B = np.array([[4, 5, 6, 7]])

# Broadcasting: A + B
result = A + B

print("Array A:")
print(A)

print("\nArray B:")
import numpy as np

# Array A with shape (3, 1)
A = np.array([[1], [2], [3]])

# Array B with shape (1, 4)
B = np.array([[4, 5, 6, 7]])

# Broadcasting: A + B
result = A + B

print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nResult of A + B (Broadcasting):")
print(result)

print(B)

print("\nResult of A + B (Broadcasting):")
print(result)

Array A:
[[1]
 [2]
 [3]]

Array B:
[[4 5 6 7]]

Result of A + B (Broadcasting):
[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]
